

###################################      ADD PRODUCT TO CART     ##########################################
POST localhost:9999/cart/16

###################################      GET ALL PRODUCTS FOR USER    #####################################
GET localhost:9999/cart

###################################      REMOVE PRODUCT FROM CART    ######################################
DELETE localhost:9999/cart/14

