
###################################      CREATE ORDER     ##########################################
POST localhost:9999/orders

##############################      GET ALL ORDERS FOR USER     ##########################################
GET localhost:9999/orders
